language: generic
dist: xenial
os: linux

git:
  depth: 1

jobs:
  include:
    - name: "Run Linters"
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python3-setuptools
      install:
        - pip install --user PyYaml -q
        - pip install --user beautifulsoup4 -q
      before_script: skip
      script:
        - shopt -s globstar
        - find . -name "*.php" -print0 | xargs -0 -n1 php -l
        - find . -name "*.json" -not -path "./nano/node_modules/*" -print0 | xargs -0 python3 ./tools/travis/json_verifier.py
        - tools/travis/build_nanoui.sh
        - tools/travis/check_grep.sh
        - tools/travis/check_changelogs.sh
        - python3 tools/travis/check_line_endings.py
        - (num=$(grep -Ern '\\(red|blue|green|black|italic|bold|b|i[^mc])' code/ | wc -l); echo "$num BYOND text macros (expecting ${BYOND_MACRO_COUNT} or fewer)"; [ $num -le ${BYOND_MACRO_COUNT} ])
        - md5sum -c - <<< "6dc1b6bf583f3bd4176b6df494caa5f1 *html/changelogs/example.yml"
        - python tools/ss13_genchangelog.py html/changelog.html html/changelogs

    - name: "Compile All Maps"
      addons:
        apt:
          packages:
            - libstdc++6:i386
      cache:
        directories:
          - $HOME/BYOND
      install:
        - tools/travis/install_byond.sh
        - source $HOME/BYOND/byond/bin/byondsetup
      script:
        - tools/travis/dm.sh -Mtravis_map_testing paradise.dme
